---
title: 'Publications'
toc: true
toc_label: 'Publications by Topic'
toc_icon: 'book'
toc-location: body

---

## Alcohol Use and Psychological Distress
1. Levine, J.A., Gius, B.K., Boghdadi, G., Connors, G.J., Maisto, S.A., & Schlauch, R.C. (in press). Between- and within-person associations between alcohol use and psychological distress during and following treatment: A Test of the bidirectional relationships. *Alcoholism: Clinical and Experimental Research.*

## Food Craving
2. Ahlich, E., Verzijl, C.L., Simon, J., Schlauch, R.C., & Rancourt, D. (in press). Support for a multidimensional model of food craving using self-report and cue reactivity methodologies. *International Journal of Eating Disorders.*

## Alcohol Approach and Avoidance
3. Noyes, E.T., Levine, J.A., & Schlauch, R.C. (2019). Psychometric evaluation of the approach and avoidance of alcohol questionnaire in a community sample. *Journal of Psychopathology and Behavioral Assessment, 41,* 375-383.
4. Levine, J.A., Noyes, E.T., Gius, B., Houston, R.J., Ahlich, E., Rancourt, D. & Schlauch, R.C. (2019). Development and Psychometric Evaluation of a Brief Approach and Avoidance of Alcohol Questionnaire. *Alcoholism: Clinical and Experimental Research, 43,* 353-366.
5. Noyes, E.T. & Schlauch, R.C. (2018). Examination of approach and avoidance inclinations on the reinforcing value of alcohol. *Addictive Behaviors, 79,* 61-67.
6. Noyes, E.T., Levine, J.A., Schlauch, R.C., Crane, C.A., Connors, G.J., Maisto, S.A., & Dearing, R.L. (2018). Impact of pretreatment change on mechanism of behavior change research: An applied example using alcohol abstinence self-efficacy. *Journal of Studies on Alcohol and Drugs, 79,* 223-228.
7. Schlauch, R.C., Levitt, A., Bradizza, C.M., Stasiewicz, P.R., Lucke, J.F., Maisto, S.A., Zhou, Y. & Connors, G.J. (2013). Alcohol Craving in Patients Diagnosed with a Severe Mental Illness and Alcohol Use Disorder: Bi-Directional Relationships between Approach and Avoidance Inclinations and Drinking. *Journal of Consulting and Clinical Psychology, 81,* 1087-1099.

## Craving and Disordered Eating Behaviors
8. Rancourt, D., Ahlich, E., Levine, J.,A., Lee, M., Schlauch, R. C., (2019). Applying a multidimensional model of craving to disordered eating behaviors: Development of an approach and avoidance questionnaire. *Psychological Assessment, 31,* 751-764.

## Craving and Alcohol Treatment
9. Schlauch, R.C., Crane, C.A., Connors, G.J., Dearing, R.L., & Maisto, S.A (2019). The Role of Craving in the Treatment of Alcohol Use Disorders: The Importance of Pretreatment Changes and Competing Desires. *Drug and Alcohol Dependence, 199,* 144-150.
10. Schlauch, R.C., Rice, S.L., Connors, G.J., & Lang, A.R. (2015). Ambivalence Model of Craving: A latent profile analysis of cue-elicited alcohol craving in an inpatient clinical sample. *Journal of Studies on Alcohol and Drugs, 76,* 764-772.
